name: Deploy to EC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPOnms164swDWtk6QmaJV+eSLfGTayEyRFDEbb7sQQq4hXVYc0l1eqk/Z0Vud5i6eNMLjG45AgRMjNPtbGgp8NowM4iW1YbXN4SWwmR65lw6WKVGlZdSOhLKeuxYDhmGx43AXM75uy33Lrl2RruX+51WvNwvlzKZJg/fZnr+diVrgaH2SXNYzdUGTffhiGp1ixh4WO12XH8FWMHnK1EQUH3k1fcOjwKyiu9a/HGrxCR8EP80RwbrFr/ZpgFLlxxXtQ1F3RrMaQ2MXms+x+4v2xjb9EI8ehHq4FhLafU50w+Uazf3XU1VPJrmdRlPxpRMb/5oNZPuMAM5ulzqIGIe6h imported-openssh-key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Install PHP and dependencies
      run: sudo apt-get update && sudo apt-get install php php-mbstring php-xml

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Deploy to EC2
      run: |
        rsync -avz --delete --exclude-from=".rsyncignore" -e "ssh -i ~/.ssh/id_rsa" ./ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/path/to/your/project
        ssh -i ~/.ssh/id_rsa ubuntu@54.237.187.18 'cd /path/to/your/project && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan config:cache && php artisan route:cache'

    - name: Clear SSH key
      run: rm ~/.ssh/id_rsa
